<template>
  <q-page class="general-bg-theme">
      <video autoplay muted loop class="myVideo" v-if=show>
        <source src="~assets/fw.mp4" type="video/mp4">
        Your browser does not support HTML5 video.
      </video>
      <div class="content">
         <span class="timer-display" v-if="timerShow">
           <span v-bind:style="{ 'color':minuteColor }"> {{ countdownMinutes }} </span>
           <span v-bind:style="{ 'color':timeColonColor }">:</span>
           <span v-bind:style="{ 'color':secondColor, 'opacity': secondOpacity }"> {{ countdownSeconds }} </span>
         </span>
      </div>
      <div class="content">
        <span class="welcome-display" v-if=welcome> Welcome to 2020</span>
        <span class="initiate-display" v-if=initiate>Happy New Year!!!</span>
      </div>
  </q-page>
</template>

<script>
export default {
  name: 'countdown',
  data () {
    return {
      countdownMinutes: 0,
      countdownSeconds: 0,
      show: false,
      minuteColor: '#bca410',
      timeColonColor: 'grey',
      secondColor: '#bca410',
      welcome: false,
      initiate: false,
      timerShow: true
    }
  },
  mounted () {
    this.timeOutClock()
  },
  methods: {
    timeOutClock () {
      var start = new Date().getTime()
      // countdown from 5 minutes
      var countdown = new Date(start + 5 * 60000)
      var x = setInterval(() => {
        var now = new Date().getTime()
        var distance = countdown - now
        this.countdownMinutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60)) < 10 ? String('0' + Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60))) : String(Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60)))
        this.countdownSeconds = Math.floor((distance % (1000 * 60)) / 1000) < 10 ? String('0' + Math.floor((distance % (1000 * 60)) / 1000)) : String(Math.floor((distance % (1000 * 60)) / 1000))
        if (distance < 60000) {
          this.minuteColor = '#bca410'
        }

        if (this.courierFoundModal === true) {
          clearInterval(x)
          return
        }

        if (distance < 1000) {
          this.show = true
          this.timerShow = false
          this.welcome = true
          setTimeout(() => {
            this.welcome = false
            this.initiate = true
          }, 10000)
          this.courierSearchTimeoutModal = true
          clearInterval(x)
        }
      })
    }
  }
}
</script>
<style lang="stylus" scoped>
.general-bg-theme
  background-color #52ACFF
  background-image linear-gradient(180deg, #52ACFF 12%, #2cfffe 50%, #ffffff 100%)

.welcome-display
  font-size 100px
  font-weight bold
  font-family 'Lobster', cursive
  -webkit-animation puff-in-top 0.8s cubic-bezier(0.470, 0.000, 0.745, 0.715) both
  animation puff-in-top 0.8s cubic-bezier(0.470, 0.000, 0.745, 0.715) both

.initiate-display
  font-size 100px
  font-weight bold
  font-family 'Ibarra Real Nova', serif
  -webkit-animation roll-in-left 0.6s ease-out both
  animation roll-in-left 0.6s ease-out both

.timer-display
  font-size 200px
  font-family 'Ibarra Real Nova', serif
  font-weight bold
  -webkit-animation fade-out-bck 1.3s cubic-bezier(0.250, 0.460, 0.450, 0.940) both
  animation fade-out-bck 1.3s cubic-bezier(0.250, 0.460, 0.450, 0.940) both
  animation-delay 301s

.myVideo
  position fixed
  right 0
  bottom 0
  min-width 100%
  min-height 100%
  -webkit-animation slide-in-fwd-center 1.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both
  animation slide-in-fwd-center 1.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both

.content
  position fixed
  top 0
  margin-top 160px
  text-align center
  background rgba(0, 0, 0, 0.1)
  color #f1f1f1
  width 100%
  padding 0

/* ----------------------------------------------
 * Generated by Animista on 2019-12-29 16:23:51
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-fwd-center
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-fwd-center {
  0% {
    -webkit-transform: translateZ(-1400px);
            transform: translateZ(-1400px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateZ(0);
            transform: translateZ(0);
    opacity: 1;
  }
}
@keyframes slide-in-fwd-center {
  0% {
    -webkit-transform: translateZ(-1400px);
            transform: translateZ(-1400px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateZ(0);
            transform: translateZ(0);
    opacity: 1;
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2019-12-29 16:35:30
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-out-bck
 * ----------------------------------------
 */
@-webkit-keyframes fade-out-bck {
  0% {
    -webkit-transform: translateZ(0);
            transform: translateZ(0);
    opacity: 1;
  }
  100% {
    -webkit-transform: translateZ(-80px);
            transform: translateZ(-80px);
    opacity: 0;
  }
}
@keyframes fade-out-bck {
  0% {
    -webkit-transform: translateZ(0);
            transform: translateZ(0);
    opacity: 1;
  }
  100% {
    -webkit-transform: translateZ(-80px);
            transform: translateZ(-80px);
    opacity: 0;
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2019-12-29 16:51:8
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation puff-in-top
 * ----------------------------------------
 */
@-webkit-keyframes puff-in-top {
  0% {
    -webkit-transform: scale(2);
            transform: scale(2);
    -webkit-transform-origin: 50% 0%;
            transform-origin: 50% 0%;
    -webkit-filter: blur(4px);
            filter: blur(4px);
    opacity: 0;
  }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
    -webkit-transform-origin: 50% 0%;
            transform-origin: 50% 0%;
    -webkit-filter: blur(0px);
            filter: blur(0px);
    opacity: 1;
  }
}
@keyframes puff-in-top {
  0% {
    -webkit-transform: scale(2);
            transform: scale(2);
    -webkit-transform-origin: 50% 0%;
            transform-origin: 50% 0%;
    -webkit-filter: blur(4px);
            filter: blur(4px);
    opacity: 0;
  }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
    -webkit-transform-origin: 50% 0%;
            transform-origin: 50% 0%;
    -webkit-filter: blur(0px);
            filter: blur(0px);
    opacity: 1;
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2019-12-29 17:2:54
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation roll-in-left
 * ----------------------------------------
 */
@-webkit-keyframes roll-in-left {
  0% {
    -webkit-transform: translateX(-800px) rotate(-540deg);
            transform: translateX(-800px) rotate(-540deg);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0) rotate(0deg);
            transform: translateX(0) rotate(0deg);
    opacity: 1;
  }
}
@keyframes roll-in-left {
  0% {
    -webkit-transform: translateX(-800px) rotate(-540deg);
            transform: translateX(-800px) rotate(-540deg);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0) rotate(0deg);
            transform: translateX(0) rotate(0deg);
    opacity: 1;
  }
}

</style>
